name: Terraform Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write    # REQUIRED for OIDC
      contents: read

    steps:
      # 1) Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configure AWS credentials using OIDC
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::698251583579:role/GitHubActionsTerraformRole
          aws-region: us-east-2

      # 3) Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4) Init Terraform (downloads providers + connects backend)
      - name: Terraform Init
        run: terraform init

      # 5) Check formatting
      - name: Terraform Fmt
        run: terraform fmt -check

      # 6) Validate configuration syntax
      - name: Terraform Validate
        run: terraform validate

      # 7) Create plan file
      - name: Terraform Plan
        run: terraform plan -out=tfplan.out

      # 8) Upload plan output as artifact
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan.out

      # 9) Apply only on manual trigger
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan.out
